apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: netcoremvc
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: netcoremvc
    spec:
      containers:
      - name: netcoremvc
        image: docker.io/elustgarten/netcoremvc
        ports:
        - containerPort: 8085